version: '3.8'

services:
  crud_movie_manager:
    build: ./
    command: ./crud_movie_manager
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
